version: 0.0
os: linux
files:
  - source: /
    destination: /var/sentry
hooks:
  AfterInstall:
    - location: /aws-codedeploy-scripts/copy_creds.sh
      timeout: 10
      runas: ec2-user
  ApplicationStart:
    - location: /aws-codedeploy-scripts/start_server.sh
      timeout: 360
  ApplicationStop:
    - location: /aws-codedeploy-scripts/stop_server.sh
      timeout: 60
