version: '2'

services:

  sentry:
    build: ./
    restart: always
    ports:
      - 80:9000
    env_file: prod_env

  sentry-cron:
    restart: always
    build: ./
    depends_on:
      - sentry
    command: "run cron"
    env_file: prod_env

  sentry-worker-1:
    restart: always
    build: ./
    depends_on:
      - sentry
    command: "run worker"
    env_file: prod_env
