version: '2'

services:
  redis:
    image: redis

  sentry:
    image: m38io/datascience-sentry
    restart: always
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 80:9000
    volumes:
      - config:/config
    environment:
      S3_CONFIG_PATH: "sentry-test-bucket/deploy-credentials-test.sh"
      CONFIG_PATH_IN: "/config/credentials.sh"

  sentry-cron:
    restart: always
    image: m38io/datascience-sentry:latest
    depends_on:
      - sentry
      - redis
    volumes:
      - config:/config
    command: "run cron"
    environment:
      CONFIG_PATH_IN: "/config/credentials.sh"

  sentry-worker-1:
    restart: always
    image: m38io/datascience-sentry:latest
    depends_on:
      - sentry
      - redis
    volumes:
      - config:/config
    command: "run worker"
    environment:
      CONFIG_PATH_IN: "/config/credentials.sh"

volumes:
  config: {}
