version: '2'

services:
  redis:
    cpu_shares: 228
    mem_limit: 301m
    image: redis

  sentry:
    image: m38io/datascience-sentry
    cpu_shares: 412
    mem_limit: 404m
    restart: always
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 80:9000
    volumes:
      - config:/config
    environment:
      S3_CONFIG_PATH: "/config/credentials.sh"

  sentry-cron:
    cpu_shares: 128
    mem_limit: 116m
    restart: always
    image: m38io/datascience-sentry
    depends_on:
      - sentry
      - redis
    volumes:
      - config:/config
    command: "run cron"
    environment:
      S3_CONFIG_PATH: "/config/credentials.sh"

  sentry-worker-1:
    cpu_shares: 128
    mem_limit: 116m
    restart: always
    image: m38io/datascience-sentry
    depends_on:
      - sentry
      - redis
    volumes:
      - config:/config
    command: "run worker"
    environment:
      S3_CONFIG_PATH: "/config/credentials.sh"

  configuration:
    image: m38io/datascience-sentry
    volumes:
      - config:/config
    cpu_shares: 128
    mem_limit: 58m
    environment:
      S3_CONFIG_PATH: "BUCKET_PATH_HERE"
      CONFIG_OUTPUT_PATH: "/config/credentials.sh"

volumes:
  config: {}
