version: '2'

services:
  redis:
    cpu_shares: 228
    mem_limit: 301m
    image: redis

  sentry:
    image: m38io/datascience-sentry:latest
    cpu_shares: 412
    mem_limit: 404m
    restart: always
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 80:9000
    volumes:
      - config:/config
    environment:
      CONFIG_PATH_IN: "deploy-credentials-test.sh"

  sentry-cron:
    cpu_shares: 128
    mem_limit: 116m
    restart: always
    image: m38io/datascience-sentry:latest
    depends_on:
      - sentry
      - redis
    volumes:
      - config:/config
    command: "run cron"
    environment:
      CONFIG_PATH_IN: "deploy-credentials-test.sh"

  sentry-worker-1:
    cpu_shares: 128
    mem_limit: 116m
    restart: always
    image: m38io/datascience-sentry:latest
    depends_on:
      - sentry
      - redis
    volumes:
      - config:/config
    command: "run worker"
    environment:
      CONFIG_PATH_IN: "deploy-credentials-test.sh"

volumes:
  config: {}
