version: '2'
services:
  redis:
    image: redis

  postgres:
    restart: always
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sentry
  
  sentry:
    build: ./
    links:
      - redis
      - postgres
    environment:
      CONFIG_PATH_IN: ""

  sentry-cron:
    build: ./
    links:
      - redis
      - postgres
    environment:
      CONFIG_PATH_IN: ""

  sentry-worker-1:
    build: ./
    links:
      - redis
      - postgres
    environment:
      CONFIG_PATH_IN: ""

# Define shared volumes
volumes:
  pgdata: {}
  config: {}
