version: '2'
services:
  redis:
    cpu_shares: 512
    mem_limit: 1058993459
    image: redis

  sentry:
    image: arn:aws:ecr:us-east-1:340827108577:repository/datascience-sentry
    cpu_shares: 512
    mem_limit: 1258993459
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 9000:9000
    volumes:
      - config:/config
    environment:
      S3_CONFIG_PATH: ""

  sentry-cron:
    cpu_shares: 256
    mem_limit: 558993459
    image: arn:aws:ecr:us-east-1:340827108577:repository/datascience-sentry
    depends_on:
      - sentry
      - redis
    volumes:
      - config:/config
    command: "run cron"

  sentry-worker-1:
    cpu_shares: 256
    mem_limit: 558993459
    image: arn:aws:ecr:us-east-1:340827108577:repository/datascience-sentry
    depends_on:
      - sentry
      - redis
    volumes:
      - config:/config
    command: "run worker"

  configuration:
    image: m38io/module.configuration:bdff373f343055d94f11081c18a33f210858e986
    volumes:
      - config:/config
    cpu_shares: 128
    mem_limit: 64m
    environment:
      S3_CONFIG_PATH: "BUCKET_PATH_HERE"
      CONFIG_OUTPUT_PATH: "/config/credentials.sh"

volumes:
  config: {}
