version: '2'
services:
  postgres:
    restart: always
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sentry
  sentry:
    links:
      - redis
      - postgres
    ports:
      - 80:9000
    environment:
      SENTRY_SECRET_KEY: 'a-super-secret-key'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis

  sentry-cron:
    environment:
      SENTRY_SECRET_KEY: 'a-super-secret-key'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis

  sentry-worker-1:
    environment:
      SENTRY_SECRET_KEY: 'a-super-secret-key'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_POSTGRES_PORT: 5432
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis

# Define shared volumes
volumes:
  pgdata: {}
