version: '2'

services:

  sentry:
    build: ./
    restart: always
    ports:
      - 80:9000
    volumes:
      - config:/config
    environment:
      S3_CONFIG_PATH: "advana-datalayer-nprd/deploy-credentials.sh"
      CONFIG_PATH_IN: "/config/credentials.sh"

  sentry-cron:
    restart: always
    build: ./
    depends_on:
      - sentry
    volumes:
      - config:/config
    command: "run cron"
    environment:
      S3_CONFIG_PATH: "advana-datalayer-nprd/deploy-credentials.sh"
      CONFIG_PATH_IN: "/config/credentials.sh"

  sentry-worker-1:
    restart: always
    build: ./
    depends_on:
      - sentry
    volumes:
      - config:/config
    command: "run worker"
    environment:
      S3_CONFIG_PATH: "advana-datalayer-nprd/deploy-credentials.sh"
      CONFIG_PATH_IN: "/config/credentials.sh"

volumes:
  config: {}
