version: '2'

services:

  sentry:
    build: ./
    restart: always
    ports:
      - 80:9000
    volumes:
      - config:/config
    env_file: .env

  sentry-cron:
    restart: always
    build: ./
    depends_on:
      - sentry
    volumes:
      - config:/config
    command: "run cron"
    env_file: .env

  sentry-worker-1:
    restart: always
    build: ./
    depends_on:
      - sentry
    volumes:
      - config:/config
    command: "run worker"
    env_file: .env
