version: '2'
services:
  redis:
    image: redis

  postgres:
    restart: always
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: local_env
  
  sentry:
    build: ./
    links:
      - redis
      - postgres
    env_file: local_env

  sentry-cron:
    build: ./
    links:
      - redis
      - postgres
    env_file: local_env

  sentry-worker-1:
    build: ./
    links:
      - redis
      - postgres
    env_file: local_env

# Define shared volumes
volumes:
  pgdata: {}
  config: {}
